In [1]:
import numpy as np


#TODO what is B hyperparameter in discretization? scBERT says 7 in their github or num tokens
def bin_microbiome_sample(abundance_vector, B=7):
    """
    Bins a single continuous 1D array of species abundances.
    abundance_vector: shape (num_species,)
    """
    # Initialize output array with zeros (Bin 0)
    binned_vector = np.zeros_like(abundance_vector, dtype=int)
    
    # Get indices of non-zero features
    non_zero_indices = np.where(abundance_vector > 0)[0]
    N = len(non_zero_indices)
    
    if N == 0:
        return binned_vector
        
    # Sort the non-zero indices by their raw abundance values descending
    # sort and return indices of the non-zero abundances in descending order
    sorted_nz_indices = non_zero_indices[np.argsort(-abundance_vector[non_zero_indices])]
    
    if N >= B:
        # Standard even splitting into B chunks
        chunks = np.array_split(sorted_nz_indices, B)
        # array_split outputs from first to last, so chunks[0] is the highest abundance
        for bin_idx, chunk in enumerate(chunks):
            actual_bin_value = B - bin_idx  # Maps chunk 0 -> Bin B, chunk B-1 -> Bin 1
            binned_vector[chunk] = actual_bin_value
    else:
        # Low diversity override: scale proportionally across 1 to B
        # Rank values scaled from 1 to B
        proportional_bins = np.linspace(B, 1, num=N).astype(int)
        for idx, actual_bin_value in zip(sorted_nz_indices, proportional_bins):
            binned_vector[idx] = actual_bin_value
            
    return binned_vector

In [2]:
B = 7
  # Initialize output array with zeros (Bin 0)
abundance_vector = np.array([
    0.02327, 0, 0.32258, 0.01651, 0, 0, 0, 0, 0, 0,
    0, 0.01443, 0, 0, 0.11799, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0.21214, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0.00036, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0.06775, 0, 0, 0,
    0, 0, 0, 0, 0, 0.04167, 0, 0, 0, 0,
    0, 0, 0.0571, 0, 0, 0.00046, 0, 0, 0, 0,
    0, 0.00206, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 1.6792, 0.43172, 0.23662, 0.59976, 0.04034, 0.03725, 0.17763, 0.59988, 0.09848,
    0.01718, 0.00889, 0.00628, 12.04134, 0.03818, 0.95354, 0.00424, 0, 13.15305, 0,
    1.41019, 0.01089, 0.44036, 0.07877, 0.00314, 0, 21.63334, 1.71746, 0.30721, 0.46523,
    0, 0.094, 0.90924, 0.11311, 0.65994, 0.58691, 0.3326, 1.08568, 0.04768, 0.77476,
    0.03452, 5.56986, 1.22835, 0.0022, 0, 0, 0, 0, 0.13671, 2.74431,
    0.65296, 0.02476, 0.03902, 0.03798, 2.62945, 0.06733, 7.45649, 0.03421, 0.00838, 0,
    0.2292, 0, 0, 0, 0.25406, 0.16928, 1.21422, 0, 1.0121, 0.9262,
    0.2025, 0, 0.23204, 0, 0, 3.41393, 0, 0, 0.00092, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 5.57945, 0.06906, 0, 0,
    0.89437, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0.01486, 0,
    0, 0, 0, 0.78645, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0.01714, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 1.65344, 0.77248, 0.17338, 0.01324, 0.01082, 0.00747, 0.00691, 0.00485, 0.00397,
    0.00074, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0
])
binned_vector = np.zeros_like(abundance_vector, dtype=int)
# 
non_zero_indices = np.where(abundance_vector > 0)[0]
print("Non-zero indices:", non_zero_indices)
sorted_nz_indices = non_zero_indices[np.argsort(-abundance_vector[non_zero_indices])]
print("Sorted non-zero indices:", sorted_nz_indices)
chunks = np.array_split(sorted_nz_indices, B)
print("Chunks:", chunks)
        # array_split outputs from first to last, so chunks[0] is the highest abundance
for bin_idx, chunk in enumerate(chunks):
    actual_bin_value = B - bin_idx  # Maps chunk 0 -> Bin B, chunk B-1 -> Bin 1
    # apply to chunks SIMD
    binned_vector[chunk] = actual_bin_value

print("Binned vector:", binned_vector)

# binned_vector = bin_microbiome_sample(abundance_vector, B=5)
# print("Original abundance vector:", abundance_vector)
# print("Binned vector:", binned_vector)

Non-zero indices: [  0   2   3  11  14  26  36  56  65  72  75  81  91  92  93  94  95  96
  97  98  99 100 101 102 103 104 105 106 108 110 111 112 113 114 116 117
 118 119 121 122 123 124 125 126 127 128 129 130 131 132 133 138 139 140
 141 142 143 144 145 146 147 148 150 154 155 156 158 159 160 162 165 168
 186 187 190 208 213 240 251 252 253 254 255 256 257 258 259 260]
Sorted non-zero indices: [116 108 103 146 186 131 165 139 144 117  91 251 110 132 156 127 158 105
 159 122 190 213 129 252 124 140  98  94 125 119 112  92 126   2 118 154
  93 162 150  26 160  97 253 155 138  14 123  99 121 113 187  56 145  72
 128  65  95 142 104 143  96 130 147 141   0 100 240   3 208  11 254 111
 255 101 148 256 257 102 258 106 259 114 133  81 168 260  75  36]
Chunks: [array([116, 108, 103, 146, 186, 131, 165, 139, 144, 117,  91, 251, 110]), array([132, 156, 127, 158, 105, 159, 122, 190, 213, 129, 252, 124, 140]), array([ 98,  94, 125, 119, 112,  92, 126,   2, 118, 154,  93, 162, 150]), array([ 26

In [29]:
vocab = set()
with open("src/token_source_attributor/data/species_vocab.txt", "r") as f:
    for line in f:
        line = line.strip()
        if line in vocab:
            print(f"Duplicate species found in vocabulary: {line}")
        vocab.add(line.strip())
print(f"Total unique species in vocabulary: {len(vocab)}")
print("Vocabulary sample:", list(vocab)[:10])

def get_species_vocab(family_str):
    return family_str.strip().split('|')[-1]
    



    


Total unique species in vocabulary: 1662
Vocabulary sample: ['k__Bacteria|p__Proteobacteria|c__Deltaproteobacteria|o__Desulfobacterales|f__Desulfobulbaceae|g__Desulfobulbus|s__Desulfobulbus_oralis', 'k__Bacteria|p__Proteobacteria|c__Alphaproteobacteria|o__Rhodobacterales|f__Rhodobacteraceae|g__Paracoccus|s__Paracoccus_sp_WN007', 'k__Bacteria|p__Proteobacteria|c__Betaproteobacteria|o__Nitrosomonadales|f__Sterolibacteriaceae|g__Methyloversatilis|s__Methyloversatilis_sp_RAC08', 'k__Bacteria|p__Proteobacteria|c__Gammaproteobacteria|o__Enterobacterales|f__Enterobacteriaceae|g__Klebsiella|s__Klebsiella_oxytoca', 'k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Lachnospiraceae|g__Johnsonella|s__Johnsonella_ignava', 'k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_pseudopneumoniae', 'k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Ruminococcaceae_unclassified|s__Clostridium_leptum', 'k__Bac

In [31]:
s = 'k__Bacteria|p__Proteobacteria|c__Deltaproteobacteria|o__Desulfobacterales|f__Desulfobulbaceae|g__Desulfobulbus|s__Desulfobulbus_oralis'

def get_species_vocab(family_str):
    return family_str.strip().split('|')[-1][3:]

get_species_vocab(s)

'Desulfobulbus_oralis'

In [44]:
# count = []
with open("src/token_source_attributor/data/bert_pretraining_stool_binned.tsv", "r") as f:
    for i, line in enumerate(f):
        line = line.strip().split("\t")
        c = sum(1 for x in line[2:])
        if c != 1662:
            print(f"Line {i} has {c} non-zero entries, expected 1662.")
        
       

        if i > 1:
            abundances = [int(x) for x in line[2:]]
            print(abundances)
            print(max(abundances), min(abundances))
        else:
            print(line[7])
        
        if i > 10:
            break
# print(count)
        


k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter|s__Methanobrevibacter_smithii
0
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [ ]:
import torch

def mask_nonzero_abundance_bins(abundance_bins, mask_bin_id, mask_prob=0.25):
    """
    abundance_bins: [B, S], values 0..50
    mask_bin_id: special input value, e.g. 51

    Returns:
        abundance_bins_masked: [B, S] -> 51 where we want to predict
        mlm_labels: [B, S], original bins at masked positions, -100 elsewhere ... this is for MSE
        masked_positions: [B, S], boolean ... not sure why this is needed 
         
    """
    # do not predict nonzero
    nonzero = abundance_bins > 0
    # deterministically and randomly select a percentage of the non zero sequence length
    random_select = torch.rand_like(abundance_bins.float()) < mask_prob

    masked_positions = nonzero & random_select

    mlm_labels = torch.full_like(abundance_bins, -100)
    mlm_labels[masked_positions] = abundance_bins[masked_positions]

    abundance_bins_masked = abundance_bins.clone()
    abundance_bins_masked[masked_positions] = mask_bin_id

    return abundance_bins_masked, mlm_labels, masked_positions



In [ ]:
a_bins = torch.tensor([
        [0, 3, 50, 4, 2, 1, 0, 0, 49, 3, 4, 1, 2, 43, 36 ],
        [ 2, 4, 3, 1, 0, 0, 0, 4, 2, 3, 1, 1, 44, 32, 7],
])
mask_nonzero = a_bins > 0
print(mask_nonzero)
# uniform distribution
mask_random = torch.rand_like(a_bins.float()) < 0.25
print(mask_random)
print('intersection')
print(mask_nonzero & mask_random)

# what about sampling from non zero positions, if bernoulli then its independent per position / token so same / stochastic gets more accurate with larget samples hence law of large numbers
# but if many are 0 then we will not sample exactly 25% of non zero samples.

# mask_nonzero_abundance_bins(a_bins, mask_bin_id=51, mask_prob=0.25)

tensor([[False,  True,  True,  True,  True,  True, False, False,  True,  True,
          True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False, False, False,  True,  True,  True,
          True,  True,  True,  True,  True]])
tensor([[False, False, False, False, False, False, False, False, False, False,
          True, False, False,  True, False],
        [ True, False, False, False, False,  True, False, False, False, False,
         False, False,  True, False,  True]])
intersection
tensor([[False, False, False, False, False, False, False, False, False, False,
          True, False, False,  True, False],
        [ True, False, False, False, False, False, False, False, False, False,
         False, False,  True, False,  True]])


In [5]:
import torch
pred_bins = torch.tensor([[0.2, 5.7, 1.1, 9.0]])
mlm_labels = torch.tensor([[-100, 6, -100, 8]])
mask = mlm_labels != -100

pred_bins[mask]

# mlm_labels[mask].float()

tensor([5.7000, 9.0000])

In [27]:
import numpy as np
mlm_output_vector = np.array([0.1,1,0.5])
mlm_output_batched = np.tile(mlm_output_vector, (4,1))

results = np.log(mlm_output_batched) * -1
avg_grad = np.sum(results)
avg_grad / 4

np.float64(2.995732273553991)

In [37]:
import torch

x = torch.tensor([-100, 5, -100, 1])
y = torch.tensor([-100, 5, -100, 0])

mask = (y != -100)

z_mask = (x != -100) & (x == 0)


z_mask.any()





tensor(False)